### ISSUE TITLE
Release installer & test

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/rockettype#39]
- release the installer
- make sure it can be installed and run on Windows
- test that the typo replacement works be typing 'someting ' which should then be transformed to 'something '
- list observations about the architecture of the application. What would you refactor to allow for longer term development of live typing correction?

>yes, this seems good to me. I think it would take me a few hours of work and I could do it by tomorrow evening

**Comment by janmechtel** [comment]
@c-iordache doesn't work for me yet:

> PS C:\Users\JanMechtel> C:\Users\JanMechtel\AppData\Local\Programs\RocketType\Python\python.exe "C:\Users\JanMechtel\AppData\Local\Programs\RocketType\RocketType.launch.pyw"
> Traceback (most recent call last):
>   File "C:\Users\JanMechtel\AppData\Local\Programs\RocketType\RocketType.launch.pyw", line 35, in <module>
>     main()
>   File "C:\Users\JanMechtel\AppData\Local\Programs\RocketType\pkgs\keylogger\logger.pyw", line 219, in main
>     __init__()
>   File "C:\Users\JanMechtel\AppData\Local\Programs\RocketType\pkgs\keylogger\logger.pyw", line 59, in __init__
>     env['typos'] = init_typos()
>   File "C:\Users\JanMechtel\AppData\Local\Programs\RocketType\pkgs\keylogger\logger.pyw", line 85, in init_typos
>     with open('commonTypos.csv', newline='') as csvfile:
> FileNotFoundError: [Errno 2] No such file or directory: 'commonTypos.csv'
> PS C:\Users\JanMechtel>
